trigger:
- main

pool:
  vmImage: ubuntu-latest

name: $(Build.DefinitionName)_$(Date:yyyyMMdd)_$(Rev:r)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: python -m pip install -r requirements.txt
  displayName: 'Install requirements'

- script: python -m pytest
  displayName: 'Run tests'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'